// Auto-generated by sync-calendar.js from Outlook + Obsidian
// Last synced: 2026-05-12T16:52:39.471Z
window.SYNCED_DATA = {
  "syncedAt": "2026-05-12T16:52:39.471Z",
  "source": "outlook+obsidian",
  "courses": {
    "mns521": {
      "lastActiveDate": "2026-04-02",
      "lastActive": "40 days ago",
      "actionItems": {
        "total": 16,
        "done": 0,
        "pending": [
          "Dariush: add point distribution to all assignments",
          "Dariush: write out full assignment details — keep \"which assignment will students be most excited about?\" in mind",
          "Dariush: list materials for each module (textbook chapters, slides, lecture videos ~5–10 min each, supplementary readings, software/tools)",
          "Dariush: consider tool-oriented assignments (e.g., Jupyter Notebook install + basic use) that blend learning material into the assignment",
          "Elisa: set up Zoom link for next meeting (April 17, 2:00 PM) — materials review only",
          "Elisa: use date-push tool (per Tamara) to populate all assignment due dates from March 18 baseline, Thursdays",
          "Elisa investigate Harmonize grade export functionality and integration options",
          "Research API token access and configuration for Harmonize integration",
          "Dariush to complete assignment planning table by March 30, 2026",
          "Schedule follow-up meeting for April 2, 2026 at 1:00 PM",
          "Create sample Module 1 assignment drafts before next Thursday meeting",
          "Elisa create sample Module 1 assignment drafts before Thursday",
          "Dariush provide faculty feedback on sample assignments",
          "Differentiate CLOs and ELOs by module to show progression",
          "Continue iterative assignment refinement process",
          "Test assignment formats in Canvas and/or Articulate Rise"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "May 12",
        "text": "Pending: add point distribution to all assignments; write out full assignment details — keep \"which assignment w; list materials for each module (textbook chapters, slides, l. Recent decisions: All assignments due on Thursdays; Spring B 2027 baseline: March 18 = first due date.",
        "source": "obsidian"
      },
      "nextMeeting": {
        "date": "2026-05-14",
        "time": "2:30 PM",
        "label": "MNS 521 - Module 2"
      },
      "milestoneStatus": [
        {
          "status": "done"
        },
        {
          "status": "done"
        },
        {
          "status": "done"
        },
        {
          "status": "meeting",
          "meetingDate": "2026-05-14",
          "meetingLabel": "May 14 at 2:30 PM"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Apr 17",
          "label": "Materials Review (2:00 PM)",
          "statusText": "14 days away"
        },
        {
          "date": "Aug 1",
          "label": "Final Walkthrough & QA",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Apr 2, 2026",
          "title": "MNS 521 Assignments Review",
          "people": [
            "Elisa Penmar",
            "Dariush"
          ],
          "summary": "- CLO #3 was missing — placeholder text removed, restored to: \"Recognize the mechanics of machine learning algorithms\" - \"Understand\" flagged as non-assessable verb in one ELO → replaced with \"explain\" (e.g., \"explain the evolution of…\") - Module objectives map to ELOs, not CLOs — but keeping CLOs clean still worthwhile - Module 6 (AI Architecture Proposal draft) feeds directly into Module 7 (final project) - Modules 2 and 4 have 4 assignments; all others have 3 — workload expected approximately",
          "decisions": [
            "All assignments due on Thursdays",
            "Spring B 2027 baseline: March 18 = first due date",
            "Harmonize auto-grading with 80/20 split (initial post / peer responses)",
            "MNS 522 = no new development needed (existing ACO 580 course)"
          ],
          "actionItems": [
            {
              "text": "Dariush: add point distribution to all assignments",
              "done": false
            },
            {
              "text": "Dariush: write out full assignment details — keep \"which assignment will students be most excited about?\" in mind",
              "done": false
            },
            {
              "text": "Dariush: list materials for each module (textbook chapters, slides, lecture videos ~5–10 min each, supplementary readings, software/tools)",
              "done": false
            },
            {
              "text": "Dariush: consider tool-oriented assignments (e.g., Jupyter Notebook install + basic use) that blend learning material into the assignment",
              "done": false
            },
            {
              "text": "Elisa: set up Zoom link for next meeting (April 17, 2:00 PM) — materials review only",
              "done": false
            },
            {
              "text": "Elisa: use date-push tool (per Tamara) to populate all assignment due dates from March 18 baseline, Thursdays",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 19, 2026",
          "title": "First Solo Meeting with Dariush",
          "people": [
            "Elisa Penmar",
            "Dariush"
          ],
          "summary": "**Decision Made**: Harmonize chosen over YellowDig for collaborative work **Reasoning**: - Better support for collaborative learning activities - More flexible assessment options - Superior grade management capabilities - Alignment with ASU Online standards Designing interactive assignment using agent models: - **Concept**: Students engage with AI agent scenarios",
          "decisions": [
            "Use Harmonize platform for assignments and collaboration",
            "Implement agent model exercise with differentiated tracks",
            "Use scenario-based assignment approach",
            "Support both in-person and online course modalities"
          ],
          "actionItems": [
            {
              "text": "Elisa investigate Harmonize grade export functionality and integration options",
              "done": false
            },
            {
              "text": "Research API token access and configuration for Harmonize integration",
              "done": false
            },
            {
              "text": "Dariush to complete assignment planning table by March 30, 2026",
              "done": false
            },
            {
              "text": "Schedule follow-up meeting for April 2, 2026 at 1:00 PM",
              "done": false
            },
            {
              "text": "Create sample Module 1 assignment drafts before next Thursday meeting",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 13, 2026",
          "title": "MNS 521 Meeting",
          "people": [
            "Elisa Penmar",
            "Dariush"
          ],
          "summary": "**Status**: 7 Course Learning Outcomes defined for MNS 521 - CLOs cover AI and intelligent agents course scope - Comprehensive coverage of learning objectives **Issue Identified**: Module objectives incorrectly identical - **Problem**: Each module's enabling learning outcomes are the same - **Root Cause**: Copy-paste error or incomplete differentiation - **Solution Needed**: Unique, progressive ELOs for each module - **Impact**: Students won't understand progression or mastery levels",
          "decisions": [
            "Use collaborative iterative design approach for assignments",
            "Explore multiple assignment formats (quizzes, interactive, scenarios)",
            "Focus on meaningful distinctions between AI and traditional software",
            "Plan for in-person and online delivery flexibility"
          ],
          "actionItems": [
            {
              "text": "Elisa create sample Module 1 assignment drafts before Thursday",
              "done": false
            },
            {
              "text": "Dariush provide faculty feedback on sample assignments",
              "done": false
            },
            {
              "text": "Differentiate CLOs and ELOs by module to show progression",
              "done": false
            },
            {
              "text": "Continue iterative assignment refinement process",
              "done": false
            },
            {
              "text": "Test assignment formats in Canvas and/or Articulate Rise",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-03-13",
          "time": "10:30 AM",
          "label": "MNS521",
          "uid": "040000008200E00074C5B7101A82E00800000000CD5057F0C5ACDC010000000000000000100000001A00465A97B2FB44A987B1465F31CF2C",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-03-13T17:30:00.000Z",
          "dtEndIso": "2026-03-13T18:00:00.000Z"
        },
        {
          "date": "2026-04-02",
          "time": "3:00 PM",
          "label": "MNS521 Assignments Review",
          "uid": "040000008200E00074C5B7101A82E00800000000FFB07094BBB7DC01000000000000000010000000B0748FA6C7066F4B86C88469263ACD69",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-04-02T22:00:00.000Z",
          "dtEndIso": "2026-04-02T22:30:00.000Z"
        },
        {
          "date": "2026-04-16",
          "time": "2:00 PM",
          "label": "MNS 521 Materials Review",
          "uid": "040000008200E00074C5B7101A82E008000000007F47C1C8F0C2DC010000000000000000100000003BE198968CBCAF4D9F0ACCA85A3E5C39",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-04-16T21:00:00.000Z",
          "dtEndIso": "2026-04-16T21:30:00.000Z"
        },
        {
          "date": "2026-04-30",
          "time": "1:30 PM",
          "label": "MNS 521 - Module 1",
          "uid": "040000008200E00074C5B7101A82E00800000000B6661353E7CDDC01000000000000000010000000089722CF9CC5464F8763AD1403CE66E0",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-04-30T20:30:00.000Z",
          "dtEndIso": "2026-04-30T21:00:00.000Z"
        },
        {
          "date": "2026-05-14",
          "time": "2:30 PM",
          "label": "MNS 521 - Module 2",
          "uid": "040000008200E00074C5B7101A82E0080000000040880B6EE7D8DC010000000000000000100000000E95B671CA6D6B49894FBBC77DF1DC40",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-14T21:30:00.000Z",
          "dtEndIso": "2026-05-14T22:30:00.000Z"
        }
      ]
    },
    "bst605": {
      "lastActiveDate": "2026-04-10",
      "lastActive": "32 days ago",
      "actionItems": {
        "total": 17,
        "done": 0,
        "pending": [
          "Send Habte email invitation to course development platform (BST 605 + BST 609 links)",
          "Habte: review and update module-level objectives and ELO tags in platform",
          "Habte: determine assignment weights",
          "Habte: list all assignments for each module before April 24th meeting",
          "Add assignment weights section to course info page in platform",
          "Fix platform bugs: ELO tagging not saving, comment display not loading, data loss on input",
          "Follow up on Canvas quiz issue (unresolved from previous discussions)",
          "Schedule Friday meeting to prepare for hack day activities",
          "Test YellowDig functionality for assignment platform consideration",
          "Coordinate Harmonize integration and grade export options",
          "Course planning worksheet completed by April 27, 2026",
          "Course learning outcomes (CLOs) defined by April 6, 2026",
          "Enabling learning outcomes (ELOs) defined by April 6, 2026",
          "Tamara's transcript reviewed as facilitator notes",
          "Research LaTeX software options for math content rendering",
          "Create kickoff meeting guide from Tamara's planning questions",
          "Module 0 (math refresher) content framework developed"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "May 12",
        "text": "Pending: Send Habte email invitation to course development platform (; review and update module-level objectives and ELO tags in pl; determine assignment weights. Recent decisions: BST 605 converting from 15-week in-person to 7.5-week online intensive (7 modules + Module 0); Midterm exam placed at end of Module 3.",
        "source": "obsidian"
      },
      "nextMeeting": {
        "date": "2026-05-12",
        "time": "1:30 PM",
        "label": "BST 605 Lecture Planning"
      },
      "milestoneStatus": [
        {
          "status": "meeting",
          "meetingDate": "2026-05-12",
          "meetingLabel": "May 12 at 1:30 PM"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Apr 6",
          "label": "CLOs and ELOs Due",
          "urgent": true,
          "statusText": "3 days away"
        },
        {
          "date": "Jul 20",
          "label": "Course Shell Due",
          "bold": true
        },
        {
          "date": "Aug 17",
          "label": "Student Access / Launch",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Apr 10, 2026",
          "title": "BST 605 - CLOs and ELOs",
          "people": [
            "Habte"
          ],
          "summary": "- Testing new web-based course development application to replace Google Doc worksheets - Platform includes automatic timeline generation, ELO/CLO alignment tools, and syllabus generation features - Final walkthrough date auto-populated as July 20th (4 weeks before fall launch) - Habte will receive email invitation to test the platform and provide feedback - Converting BST 605 from 15-week in-person format to 7.5-week online intensive - Online students expected to complete 13–17 hours of coursew",
          "decisions": [
            "BST 605 converting from 15-week in-person to 7.5-week online intensive (7 modules + Module 0)",
            "Midterm exam placed at end of Module 3",
            "Linear mixed models included in Module 7 (repeated measures)",
            "BST 609 (Fall B) to be developed in parallel"
          ],
          "actionItems": [
            {
              "text": "Send Habte email invitation to course development platform (BST 605 + BST 609 links)",
              "done": false
            },
            {
              "text": "Habte: review and update module-level objectives and ELO tags in platform",
              "done": false
            },
            {
              "text": "Habte: determine assignment weights",
              "done": false
            },
            {
              "text": "Habte: list all assignments for each module before April 24th meeting",
              "done": false
            },
            {
              "text": "Add assignment weights section to course info page in platform",
              "done": false
            },
            {
              "text": "Fix platform bugs: ELO tagging not saving, comment display not loading, data loss on input",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 20, 2026",
          "title": "Tamara Check-In",
          "people": [
            "Elisa Penmar",
            "Tamara Mitchell"
          ],
          "summary": "Discussion of how to structure and facilitate kickoff meetings with faculty new to online course design: - Balancing faculty concerns with instructional design expertise - Managing varying levels of faculty preparation and readiness - Using backstory and context setting for new faculty - Collaborative versus directive facilitation approaches - Reviewing kickoff meeting facilitation approach - Faculty (Habte) readiness assessment and support needed - Statistical course content considerations",
          "decisions": [
            "Implement daily FYI app check as new communication protocol",
            "Proceed with Sentana Canvas integration",
            "Continue PDF remediation tool development",
            "Advance Canvas Skills package consolidation"
          ],
          "actionItems": [
            {
              "text": "Follow up on Canvas quiz issue (unresolved from previous discussions)",
              "done": false
            },
            {
              "text": "Schedule Friday meeting to prepare for hack day activities",
              "done": false
            },
            {
              "text": "Test YellowDig functionality for assignment platform consideration",
              "done": false
            },
            {
              "text": "Coordinate Harmonize integration and grade export options",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 20, 2026",
          "title": "BST 605 Course Kick-Off",
          "people": [
            "Elisa Penmar",
            "Tamara Mitchell",
            "Habte"
          ],
          "summary": "- **Course Code**: BST 605 - **Title**: Statistical Principles of Clinical Trials - **Format**: Online (converting from in-person) - **Target Launch**: Fall 2026 (Fall A semester) - **Faculty Lead**: Habte (experienced instructor) - **Course Shell Due**: July 20, 2026 - **Student Access**: August 17, 2026 - **CLOs/ELOs Due**: April 6, 2026",
          "decisions": [
            "Use backwards design methodology for course development",
            "Implement multiple assessment formats (assignments, homework, exams, projects)",
            "Create math refresher module for student support",
            "Follow ASU Online course shell requirements (due July 20)",
            "Establish April 6 as interim checkpoint for CLOs/ELOs definition"
          ],
          "actionItems": [
            {
              "text": "Course planning worksheet completed by April 27, 2026",
              "done": false
            },
            {
              "text": "Course learning outcomes (CLOs) defined by April 6, 2026",
              "done": false
            },
            {
              "text": "Enabling learning outcomes (ELOs) defined by April 6, 2026",
              "done": false
            },
            {
              "text": "Tamara's transcript reviewed as facilitator notes",
              "done": false
            },
            {
              "text": "Research LaTeX software options for math content rendering",
              "done": false
            },
            {
              "text": "Create kickoff meeting guide from Tamara's planning questions",
              "done": false
            },
            {
              "text": "Module 0 (math refresher) content framework developed",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-03-20",
          "time": "12:00 PM",
          "label": "BST 605 Course Development Kickoff",
          "uid": "040000008200E00074C5B7101A82E0080000000078DFDD5CF5B1DC0100000000000000001000000077AC876046CB264CB6BA4FF889E053A2",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-03-20T19:00:00.000Z",
          "dtEndIso": "2026-03-20T20:00:00.000Z"
        },
        {
          "date": "2026-04-10",
          "time": "1:00 AM",
          "label": "60-min Meeting - Habte Tadesse LIKASSA",
          "uid": "040000008200E00074C5B7101A82E00800000000B48AAF380DC6DC0100000000000000001000000063657800CFCA0245B8763307F05AFBBF",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-10T08:00:00.000Z",
          "dtEndIso": "2026-04-10T09:00:00.000Z"
        },
        {
          "date": "2026-04-10",
          "time": "8:00 AM",
          "label": "BST 605 - CLOs and ELOs",
          "uid": "040000008200E00074C5B7101A82E00800000000191097E09FC6DC010000000000000000100000002860E4E88F690947BD448FAA4D0FCCE5",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-10T15:00:00.000Z",
          "dtEndIso": "2026-04-10T16:00:00.000Z"
        },
        {
          "date": "2026-04-24",
          "time": "8:00 AM",
          "label": "BST 605 Assignment Review ",
          "uid": "040000008200E00074C5B7101A82E008000000008B9D911901C9DC010000000000000000100000001509B2ECA82B724C989D941C3F6E1111",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-04-24T15:00:00.000Z",
          "dtEndIso": "2026-04-24T15:30:00.000Z"
        },
        {
          "date": "2026-05-01",
          "time": "2:30 PM",
          "label": "BST605 - Materials and Alignment",
          "uid": "040000008200E00074C5B7101A82E008000000004735321203D4DC01000000000000000010000000596493E2346017479F9070F4E358D8C9",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-05-01T21:30:00.000Z",
          "dtEndIso": "2026-05-01T22:30:00.000Z"
        },
        {
          "date": "2026-05-06",
          "time": "11:30 AM",
          "label": "BST 605 Development Meeting",
          "uid": "040000008200E00074C5B7101A82E008000000000BED54BFF2DBDC01000000000000000010000000A7260CEA8F50FC4E9531473C28545752",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-05-06T18:30:00.000Z",
          "dtEndIso": "2026-05-06T19:30:00.000Z"
        },
        {
          "date": "2026-05-12",
          "time": "1:30 PM",
          "label": "BST 605 Lecture Planning",
          "uid": "2f974shcorbevp1alpg0q598d2@google.com",
          "durationMinutes": 30,
          "past": false,
          "dtStartIso": "2026-05-12T20:30:00.000Z",
          "dtEndIso": "2026-05-12T21:00:00.000Z"
        },
        {
          "date": "2026-05-19",
          "time": "1:00 PM",
          "label": "BST 605 - Alignment Overview",
          "uid": "040000008200E00074C5B7101A82E00800000000DDACCF888EDDDC01000000000000000010000000A98B83603963D5408F46CF207C4D74CC",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-19T20:00:00.000Z",
          "dtEndIso": "2026-05-19T21:00:00.000Z"
        }
      ]
    },
    "bst606": {
      "lastActiveDate": "2026-03-30",
      "lastActive": "43 days ago",
      "actionItems": {
        "total": 4,
        "done": 0,
        "pending": [
          "Send Google Drive access, slideshow, and course development worksheet via email (Elisa)",
          "Faculty complete ELOs and CLOs independently",
          "Review submitted ELOs/CLOs",
          "Explore MasterClass workshop for Yunro (quarterly availability)"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "May 12",
        "text": "Pending: Send Google Drive access, slideshow, and course development ; Faculty complete ELOs and CLOs independently; Review submitted ELOs/CLOs. Recent decisions: Communication primarily via email unless meetings needed for complex items; Backward design approach for course development.",
        "source": "obsidian"
      },
      "nextMeeting": {
        "date": "2026-06-10",
        "time": "1:00 PM",
        "label": "BST 606 -  Alignment Check-in"
      },
      "milestoneStatus": [
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Sep 14",
          "label": "QA Deadline",
          "bold": true
        },
        {
          "date": "Oct 14",
          "label": "Session B Launch — Student Access",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Mar 30, 2026",
          "title": "BST 606 Yunro Chung Kickoff",
          "people": [
            "Elisa Penmar",
            "Yunro Chung"
          ],
          "summary": "- ASU Digital Learning provides collaborative partnership throughout entire process - Support continues after course launch, not just pre-launch - Quality assurance embedded throughout - Four key support areas: instructional designers, academic media team, learning technologies, faculty support group - Backward design methodology: objectives → assessments → learning materials - Course must be ready 4 weeks before launch for QA review - Fall Session B starts October 14, 2026 — QA deadline Septemb",
          "decisions": [
            "Communication primarily via email unless meetings needed for complex items",
            "Backward design approach for course development",
            "Shared Google Drive for collaboration"
          ],
          "actionItems": [
            {
              "text": "Send Google Drive access, slideshow, and course development worksheet via email (Elisa)",
              "done": false
            },
            {
              "text": "Faculty complete ELOs and CLOs independently",
              "done": false
            },
            {
              "text": "Review submitted ELOs/CLOs",
              "done": false
            },
            {
              "text": "Explore MasterClass workshop for Yunro (quarterly availability)",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-03-30",
          "time": "9:30 AM",
          "label": "BST 606 Course Development Kickoff",
          "uid": "040000008200E00074C5B7101A82E008000000009B1542DB0BB6DC01000000000000000010000000CC54B7A19467CA44AA0D95EF92BAB2F4",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-03-30T16:30:00.000Z",
          "dtEndIso": "2026-03-30T17:30:00.000Z"
        },
        {
          "date": "2026-04-06",
          "time": "8:30 AM",
          "label": "Send email follow up for BST 606",
          "uid": "040000008200E00074C5B7101A82E00800000000CA5923B5DCC2DC010000000000000000100000002404B511998B3B4E962598059F9602C4",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-04-06T15:30:00.000Z",
          "dtEndIso": "2026-04-06T16:00:00.000Z"
        },
        {
          "date": "2026-06-10",
          "time": "1:00 PM",
          "label": "BST 606 -  Alignment Check-in",
          "uid": "040000008200E00074C5B7101A82E00800000000D695F21C2FD4DC01000000000000000010000000067FCA514492014BBCA344444E2BB18D",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-06-10T20:00:00.000Z",
          "dtEndIso": "2026-06-10T21:00:00.000Z"
        }
      ]
    },
    "tph552": {
      "lastActiveDate": "2026-04-02",
      "lastActive": "40 days ago",
      "actionItems": {
        "total": 4,
        "done": 0,
        "pending": [
          "Vienna: confirm with Ina that she's comfortable with the collapsed objectives structure",
          "Vienna: clean up and finalize the course map at next meeting",
          "Vienna: resolve notes column in the mapping document",
          "Elisa: continue development of assignments overview and materials overview pages (drag-between-modules feature in progress)"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "May 12",
        "text": "Pending: confirm with Ina that she's comfortable with the collapsed o; clean up and finalize the course map at next meeting; resolve notes column in the mapping document. Recent decisions: Designing as 7.5-week course (condensed from 15-week in-person); Module 12 assignments become Module 7 in new structure.",
        "source": "obsidian"
      },
      "nextMeeting": null,
      "milestoneStatus": [],
      "milestones": [],
      "meetings": [
        {
          "date": "Apr 2, 2026",
          "title": "TPH 552",
          "people": [
            "Elisa Penmar"
          ],
          "summary": "- Vienna teaching existing in-person version; now designing the in-person/online course - Not due until Summer 2027 — she's starting early - SAFE-aligned course; existing 15-week model being redesigned as 7.5-week course - Course map reviewed and approved by Ina and the program lead - Remaining step: confirm Ina is comfortable with how objectives were collapsed - Everything maps to ELOs, not CLOs — CLOs are essentially a list of topics being taught - ELOs = what students must do; CLOs = what nee",
          "decisions": [
            "Designing as 7.5-week course (condensed from 15-week in-person)",
            "Module 12 assignments become Module 7 in new structure"
          ],
          "actionItems": [
            {
              "text": "Vienna: confirm with Ina that she's comfortable with the collapsed objectives structure",
              "done": false
            },
            {
              "text": "Vienna: clean up and finalize the course map at next meeting",
              "done": false
            },
            {
              "text": "Vienna: resolve notes column in the mapping document",
              "done": false
            },
            {
              "text": "Elisa: continue development of assignments overview and materials overview pages (drag-between-modules feature in progress)",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-04-02",
          "time": "2:00 PM",
          "label": "TPH 552",
          "uid": "040000008200E00074C5B7101A82E0080000000001B1BE7CE4B7DC010000000000000000100000005F5E3D3FF026C5478702989CC3C1A7C6",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-04-02T21:00:00.000Z",
          "dtEndIso": "2026-04-02T21:30:00.000Z"
        }
      ]
    },
    "tph557": {
      "calendarMeetings": [
        {
          "date": "2026-04-07",
          "time": "1:00 PM",
          "label": "TPH 557 Course Development Kickoff",
          "uid": "040000008200E00074C5B7101A82E008000000003C96D31364B2DC010000000000000000100000006AC360D060A4804FA17503C34019CF74",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-07T20:00:00.000Z",
          "dtEndIso": "2026-04-07T21:00:00.000Z"
        },
        {
          "date": "2026-04-23",
          "time": "11:00 AM",
          "label": "TPH 557 - Module Objective Allignment",
          "uid": "040000008200E00074C5B7101A82E008000000000006834CD2C6DC010000000000000000100000007E46AADE2426A543A82A1A698CDDF3C3",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-23T18:00:00.000Z",
          "dtEndIso": "2026-04-23T19:00:00.000Z"
        },
        {
          "date": "2026-05-21",
          "time": "2:30 PM",
          "label": "TPH 557 - Assignments and Materials Review",
          "uid": "040000008200E00074C5B7101A82E00800000000CEEC4BF051D3DC0100000000000000001000000028998A5EDA6BDC468CC2F46B55C958E9",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-21T21:30:00.000Z",
          "dtEndIso": "2026-05-21T22:30:00.000Z"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-21",
        "time": "2:30 PM",
        "label": "TPH 557 - Assignments and Materials Review"
      },
      "meetings": [
        {
          "date": "Apr 7, 2026",
          "title": "TPH 557 Course Development Kickoff",
          "people": [
            "Elisa Penmar",
            "Tamara Mitchell",
            "Rachel Gur-Arie"
          ],
          "summary": "- **Course Code**: TPH 557 - **Title**: PH Tech Ethics, Policy and Law - **Format**: Online (converting from in-person) - **Target Launch**: Fall 2026 (need confirmation if Fall A or Fall B) - **Faculty Lead**: Rachel Gur-Arie - **Structure**: 7-week accelerated format (up to 18 hours/week) - Previously taught HCR 210 online ethics for nursing college - Split 50% appointment between FCPH and nursing college",
          "decisions": [
            "Use backwards design methodology for course development",
            "Implement video-based discussions via Flipgrid/Harmonize",
            "Explore podcast format for each module",
            "Plan media production early for fall timeline"
          ],
          "actionItems": [
            {
              "text": "Rachel: complete course development worksheet",
              "done": false
            },
            {
              "text": "Rachel: include enrollment caps information",
              "done": false
            },
            {
              "text": "Rachel: map topics for 7-module structure and define module objectives",
              "done": false
            },
            {
              "text": "Clarify accreditation-required assignments with program",
              "done": false
            },
            {
              "text": "Resolve teaching assignment conflict between colleges",
              "done": false
            },
            {
              "text": "Confirm if Fall A or Fall B launch",
              "done": false
            },
            {
              "text": "Schedule media planning early for fall production timeline",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "actionItems": {
        "total": 7,
        "done": 0,
        "pending": [
          "Rachel: complete course development worksheet",
          "Rachel: include enrollment caps information",
          "Rachel: map topics for 7-module structure and define module objectives",
          "Clarify accreditation-required assignments with program",
          "Resolve teaching assignment conflict between colleges",
          "Confirm if Fall A or Fall B launch",
          "Schedule media planning early for fall production timeline"
        ]
      },
      "lastActiveDate": "2026-04-07",
      "lastActive": "35 days ago",
      "notes": {
        "author": "Elisa Penmar",
        "date": "May 12",
        "text": "Pending: complete course development worksheet; include enrollment caps information; map topics for 7-module structure and define module objectiv. Recent decisions: Use backwards design methodology for course development; Implement video-based discussions via Flipgrid/Harmonize.",
        "source": "obsidian"
      }
    },
    "tph550": {
      "calendarMeetings": [
        {
          "date": "2026-04-06",
          "time": "2:00 PM",
          "label": "TPH Loughman Course Development Kickoff",
          "uid": "040000008200E00074C5B7101A82E008000000005C923461CEB7DC0100000000000000001000000064A3D68B2AD2B44AB85763C77040B0B7",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-06T21:00:00.000Z",
          "dtEndIso": "2026-04-06T22:00:00.000Z"
        },
        {
          "date": "2026-04-23",
          "time": "10:00 AM",
          "label": "TPH 550 Devo Meeting",
          "uid": "040000008200E00074C5B7101A82E0080000000028CB520511C6DC01000000000000000010000000C8667B0A1A520342BBC8CA1F6F20406E",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-23T17:00:00.000Z",
          "dtEndIso": "2026-04-23T18:00:00.000Z"
        },
        {
          "date": "2026-05-06",
          "time": "10:30 AM",
          "label": "TPH 550 - Assignments Overview",
          "uid": "040000008200E00074C5B7101A82E008000000004427958A0CDCDC010000000000000000100000004255D5E0E4216246AB73F48E280006FF",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-05-06T17:30:00.000Z",
          "dtEndIso": "2026-05-06T18:30:00.000Z"
        },
        {
          "date": "2026-05-14",
          "time": "1:30 PM",
          "label": "TPH 550 - Materials Review",
          "uid": "040000008200E00074C5B7101A82E00800000000512F49D585DDDC010000000000000000100000001D80659324BD064E80021B5BEEA89EDA",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-14T20:30:00.000Z",
          "dtEndIso": "2026-05-14T21:30:00.000Z"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-14",
        "time": "1:30 PM",
        "label": "TPH 550 - Materials Review"
      },
      "lastActiveDate": "2026-04-23",
      "lastActive": "7 days ago",
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 30",
        "text": "[ ] AI Task Force [ ] EDL AI Task Force [ ] BST [ ] ITAC [x] TPH [ ] CHS General [ ] POP [ ] LSC / STP [ ] MNS [ ] Program Transitioning [ ] Other: **People** (check all present): [x] Other: Josh Loughman [ ] Amanda Gulley [ ] Auryan Ratliff [ ] Bernard Johnson Jr [ ] Brent Espineda [ ] Dariush Navabi [ ] Habte Tadesse [ ] Lauren Sosa Leo [ ] Matthew Robinson [ ] Michael Arseneault [ ] Michael Duah [ ] Michael Miller [ ] Patrick White [ ] Rockell Schmidt [ ] Ron Carranza [ ] Tamara Mitchell [ ] Wayne Anderson [ ] Wesley Fleming [ ] Yunro Chung [ ] Rache Gur-Arie [ ] Josh Louchman [ ] Josh Anbar [ ] Tiffany Lemon **Follow-up Meeting Scheduled For**:",
        "source": "granola"
      },
      "meetings": [
        {
          "date": "Apr 23, 2026",
          "title": "TPH 550 online course development planning with Josh",
          "people": [
            "Other: Josh Loughman"
          ],
          "summary": "[ ] AI Task Force [ ] EDL AI Task Force [ ] BST [ ] ITAC [x] TPH [ ] CHS General [ ] POP [ ] LSC / STP [ ] MNS [ ] Program Transitioning [ ] Other: **People** (check all present): [x] Other: Josh Loughman [ ] Amanda Gulley [ ] Auryan Ratliff [ ] Bernard Johnson Jr [ ] Brent Espineda [ ] Dariush Navabi [ ] Habte Tadesse [ ] Lauren Sosa Leo [ ] Matthew Robinson [ ] Michael Arseneault [ ] Michael Duah [ ] Michael Miller [ ] Patrick White [ ] Rockell Schmidt [ ] Ron Carranza [ ] Tamara Mitchell [ ] Wayne Anderson [ ] Wesley Fleming [ ] Yunro Chung [ ] Rache Gur-Arie [ ] Josh Louchman [ ] Josh Anbar [ ] Tiffany Lemon **Follow-up Meeting Scheduled For**:",
          "decisions": [
            "Course will use Python exclusively instead of R and Python combination",
            "Susan Robinson will participate through interview-style podcast recordings rather than co-development",
            "Module zero will be added as Python bootcamp with existing online resources",
            "Lecture recordings must be completed by week of June 22nd (before Josh’s Europe trip June 28 - July 27)",
            "Course development will follow 4-week paired module schedule: weeks for modules 1, 2-3, 4-5, and 6-7",
            "Students will use publicly available data for final projects instead of restricted AZHS data",
            "AI iteration will be built into coding assignments as formal requirement with reflection components"
          ],
          "relationshipBuilding": [
            "Josh has a rabbit that was “attacking” him during the meeting for attention",
            "Taking a short weekend vacation starting tomorrow morning before his longer Europe trip",
            "Works at Decision Theater as his main job, which developed the 7-screen data exploration tool",
            "Going to Europe June 28 - July 27, returns to work July 27th",
            "Recently had a photo shoot for STPH featuring the decision theater screens",
            "Describes his teaching approach as “street fighting data science” - practical skills over software engineering"
          ],
          "actionItems": [
            {
              "text": "Elisa: Send follow-up email with link to Josh’s version of module objectives document for commenting",
              "done": false,
              "who": "id"
            },
            {
              "text": "Elisa: Create module zero for Python bootcamp materials",
              "done": false,
              "who": "id"
            },
            {
              "text": "Elisa: Update all module objectives to remove R references and focus on Python only",
              "done": false,
              "who": "id"
            },
            {
              "text": "Elisa: Research ASU’s Create AI platform capabilities for guided coding assistance",
              "done": false,
              "who": "id"
            },
            {
              "text": "Elisa: Confirm student access to ChatGPT enterprise version includes Codex",
              "done": false,
              "who": "id"
            },
            {
              "text": "Josh: Review and validate AI-generated ELO alignment mappings for all modules",
              "done": false,
              "who": "faculty"
            },
            {
              "text": "Josh: Check with decision theater about static version access for data exploration tool",
              "done": false,
              "who": "faculty"
            },
            {
              "text": "Josh: Explore CDC public data mapping tools as alternative to decision theater platform",
              "done": false,
              "who": "faculty"
            },
            {
              "text": "Josh: Review assignments overview and provide feedback before next meeting",
              "done": false,
              "who": "faculty"
            }
          ],
          "granola": "https://notes.granola.ai/d/e5af5374-1a93-4043-a469-c0a0e316bbcb",
          "transcriptUrl": "https://notes.granola.ai/t/9fe2e33c-42bf-4acb-ac4c-554e05758640",
          "source": "Granola"
        }
      ],
      "actionItems": {
        "total": 9,
        "done": 0,
        "pending": [
          "Elisa: Send follow-up email with link to Josh’s version of module objectives document for commenting",
          "Elisa: Create module zero for Python bootcamp materials",
          "Elisa: Update all module objectives to remove R references and focus on Python only",
          "Elisa: Research ASU’s Create AI platform capabilities for guided coding assistance",
          "Elisa: Confirm student access to ChatGPT enterprise version includes Codex",
          "Josh: Review and validate AI-generated ELO alignment mappings for all modules",
          "Josh: Check with decision theater about static version access for data exploration tool",
          "Josh: Explore CDC public data mapping tools as alternative to decision theater platform",
          "Josh: Review assignments overview and provide feedback before next meeting"
        ]
      }
    },
    "tph501": {
      "calendarMeetings": [
        {
          "date": "2026-04-17",
          "time": "3:00 PM",
          "label": "TPH 501",
          "uid": "040000008200E00074C5B7101A82E00800000000F7E12A402DC9DC01000000000000000010000000B20FEBBD3FB60447AC18EF09FE7D9F0C",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-17T22:00:00.000Z",
          "dtEndIso": "2026-04-17T23:00:00.000Z"
        },
        {
          "date": "2026-04-22",
          "time": "9:00 AM",
          "label": "TPH 501 - Assignments",
          "uid": "040000008200E00074C5B7101A82E00800000000A01D8CB3BACEDC01000000000000000010000000826A6F43A4CCA4468B3FFEB5A836AFC0",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-22T16:00:00.000Z",
          "dtEndIso": "2026-04-22T17:00:00.000Z"
        },
        {
          "date": "2026-05-01",
          "time": "9:00 AM",
          "label": "TPH 501 - Module 1",
          "uid": "040000008200E00074C5B7101A82E0080000000001C909BC78D2DC0100000000000000001000000079739A495731D34D93EB73DAFECA3D4E",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-05-01T16:00:00.000Z",
          "dtEndIso": "2026-05-01T17:00:00.000Z"
        },
        {
          "date": "2026-05-06",
          "time": "9:00 AM",
          "label": "TPH 501 - Alignment Audit",
          "uid": "040000008200E00074C5B7101A82E00800000000FE84C5428CD9DC01000000000000000010000000247509CC6E8AA945BA9AE9FFDA9B748C",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-05-06T16:00:00.000Z",
          "dtEndIso": "2026-05-06T17:00:00.000Z"
        },
        {
          "date": "2026-05-07",
          "time": "3:30 PM",
          "label": "TPH 501 Review",
          "uid": "040000008200E00074C5B7101A82E008000000003BCF055543DEDC01000000000000000010000000CE7A4C397D24324B8B837DEF41693E14",
          "durationMinutes": 30,
          "past": true,
          "dtStartIso": "2026-05-07T22:30:00.000Z",
          "dtEndIso": "2026-05-07T23:00:00.000Z"
        },
        {
          "date": "2026-05-21",
          "time": "8:30 AM",
          "label": "TPH 501 - Check-in",
          "uid": "040000008200E00074C5B7101A82E008000000007A0D1F457ADDDC010000000000000000100000001A3C3A30ACF7704FA0F91412257677E8",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-21T15:30:00.000Z",
          "dtEndIso": "2026-05-21T16:30:00.000Z"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-21",
        "time": "8:30 AM",
        "label": "TPH 501 - Check-in"
      },
      "meetings": [
        {
          "date": "Apr 22, 2026",
          "title": "TPH 501 - Assignments",
          "people": [
            "Other: Josh Anbar (instructor for TPH 501)"
          ],
          "summary": "Course transitioning from 15-week to 7-week format while maintaining all content. 7 modules regardless of delivery format (in-person or online). In-person students cover half of module content per week. Online students complete full modules weekly",
          "decisions": [],
          "relationshipBuilding": [],
          "actionItems": [],
          "granola": "https://notes.granola.ai/d/dc2e3cdb-b1a5-4683-897b-4ce240318909",
          "transcriptUrl": "https://notes.granola.ai/t/4cf59a7e-b7de-4b77-aafa-785dbb70cb63",
          "source": "Granola"
        },
        {
          "date": "Apr 17, 2026",
          "title": "TPH 501 course development with Josh and Jordan",
          "people": [
            "Tamara Mitchell",
            "Other: Josh Anbar"
          ],
          "summary": "TPH 501 is undergoing complete redevelopment for both online and in-person delivery. Course must be completed by August for fall launch. ASU Online requires materials 4 weeks prior to launch (approximately July 23rd). This represents a complete redesign, not just updates to existing course",
          "decisions": [],
          "relationshipBuilding": [],
          "actionItems": [],
          "granola": "https://notes.granola.ai/d/c065a381-c7db-4edb-82d2-9b13713f177f",
          "transcriptUrl": "https://notes.granola.ai/t/910e7332-f8fb-47eb-8b11-417e82e31318",
          "source": "Granola"
        }
      ],
      "actionItems": {
        "total": 0,
        "done": 0,
        "pending": []
      },
      "lastActiveDate": "2026-04-22",
      "lastActive": "8 days ago",
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 30",
        "text": "Course transitioning from 15-week to 7-week format while maintaining all content. 7 modules regardless of delivery format (in-person or online). In-person students cover half of module content per week. Online students complete full modules weekly",
        "source": "granola"
      }
    },
    "tph585": {
      "calendarMeetings": [
        {
          "date": "2026-05-12",
          "time": "11:30 AM",
          "label": "Capstone Celebration! RSVP Today!",
          "uid": "040000008200E00074C5B7101A82E0080000000030F376128EC3DC010000000000000000100000002405621BEC5A624ABD71B605B4349FEF",
          "durationMinutes": 120,
          "past": false,
          "dtStartIso": "2026-05-12T18:30:00.000Z",
          "dtEndIso": "2026-05-12T20:30:00.000Z"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-12",
        "time": "11:30 AM",
        "label": "Capstone Celebration! RSVP Today!"
      }
    },
    "pop644": {
      "calendarMeetings": [
        {
          "date": "2026-04-23",
          "time": "1:00 PM",
          "label": "POP 644 - Course Kickoff ",
          "uid": "040000008200E00074C5B7101A82E008000000007611627375CEDC010000000000000000100000008D02DA2F30321441952B402856F9273D",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-04-23T20:00:00.000Z",
          "dtEndIso": "2026-04-23T21:00:00.000Z"
        },
        {
          "date": "2026-05-01",
          "time": "1:00 PM",
          "label": "POP644 - MLO Review",
          "uid": "040000008200E00074C5B7101A82E008000000004F3594BD63D3DC0100000000000000001000000046384778CA59C44C81CAA186DDC0E5BA",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-05-01T20:00:00.000Z",
          "dtEndIso": "2026-05-01T21:00:00.000Z"
        },
        {
          "date": "2026-05-08",
          "time": "1:00 PM",
          "label": "POP 644 - Assignments and Materials",
          "uid": "040000008200E00074C5B7101A82E00800000000C1B724EF63D3DC01000000000000000010000000FE10346AAEB083438FBD45042FE45477",
          "durationMinutes": 60,
          "past": true,
          "dtStartIso": "2026-05-08T20:00:00.000Z",
          "dtEndIso": "2026-05-08T21:00:00.000Z"
        },
        {
          "date": "2026-05-15",
          "time": "1:00 PM",
          "label": "POP 644 - Development Meeting",
          "uid": "040000008200E00074C5B7101A82E0080000000025C6622364D3DC01000000000000000010000000A4011375B029304C91365F4AABCC12DA",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-15T20:00:00.000Z",
          "dtEndIso": "2026-05-15T21:00:00.000Z"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-15",
        "time": "1:00 PM",
        "label": "POP 644 - Development Meeting"
      },
      "meetings": [
        {
          "date": "Apr 23, 2026",
          "title": "POP 644 - Course Kickoff ",
          "people": [
            "Other: Tiffany Lemon",
            "Tiffany Lemon"
          ],
          "summary": "[ ] AI Task Force [ ] EDL AI Task Force [ ] BST [ ] ITAC [ ] TPH [ ] CHS General [x] POP [ ] LSC / STP [ ] MNS [ ] Program Transitioning [ ] Other: **People** (check all present): [x] Other: Tiffany Lemon [ ] Amanda Gulley [ ] Auryan Ratliff [ ] Bernard Johnson Jr [ ] Brent Espineda [ ] Dariush Navabi [ ] Habte Tadesse [ ] Lauren Sosa Leo [ ] Matthew Robinson [ ] Michael Arseneault [ ] Michael Duah [ ] Michael Miller [ ] Patrick White [ ] Rockell Schmidt [ ] Ron Carranza [ ] Tamara Mitchell [ ] Wayne Anderson [ ] Wesley Fleming [ ] Yunro Chung [ ] Rache Gur-Arie [ ] Josh Louchman [ ] Josh Anbar [x] Tiffany Lemon **Follow-up Meeting Scheduled For**:",
          "decisions": [
            "Course will be condensed from 15-week format to 7-week online format",
            "Standing meetings will be Fridays at 1:00 PM instead of Thursdays due to scheduling conflicts",
            "Will use collaborative approach with regular brainstorming sessions rather than solo work",
            "Course will incorporate AI tools as additive learning partners rather than policing their use",
            "Will build interactivity into course foundation rather than layering on top"
          ],
          "relationshipBuilding": [
            "Getting married in August 2026, currently in wedding planning mode",
            "Prefers slumber party style bachelorette celebration over destination parties",
            "Previously served in AmeriCorps for one year",
            "Spent time in Rwanda working with Peace Corps volunteers",
            "Has experience with notebook LM and is a fan of AI tools",
            "Moved to ASU from postdoc position at Mass General in Boston",
            "Loves Arizona quality of life and ASU’s forward-moving innovation culture"
          ],
          "actionItems": [
            {
              "text": "Tiffany: Review and revise module level objectives by Friday meeting",
              "done": false,
              "who": "faculty"
            },
            {
              "text": "Tiffany: Consider alternative arrangements for screening tests placement in curriculum",
              "done": false,
              "who": "faculty"
            },
            {
              "text": "Elisa: Send slideshow presentation materials to Tiffany",
              "done": false,
              "who": "id"
            },
            {
              "text": "Elisa: Send link to course development worksheet tool",
              "done": false,
              "who": "id"
            },
            {
              "text": "Elisa: Set up standing Friday 1:00 PM meetings going forward",
              "done": false,
              "who": "id"
            },
            {
              "text": "Tiffany: Consider signing up for Master Class for Teaching (June or September sessions)",
              "done": false,
              "who": "faculty"
            }
          ],
          "granola": "https://notes.granola.ai/d/d2ee1632-931b-4eb2-ba1f-194de72fe2d2",
          "transcriptUrl": "https://notes.granola.ai/t/94041e17-aff2-4c60-9603-39465d75a0ed",
          "source": "Granola"
        }
      ],
      "actionItems": {
        "total": 6,
        "done": 0,
        "pending": [
          "Tiffany: Review and revise module level objectives by Friday meeting",
          "Tiffany: Consider alternative arrangements for screening tests placement in curriculum",
          "Elisa: Send slideshow presentation materials to Tiffany",
          "Elisa: Send link to course development worksheet tool",
          "Elisa: Set up standing Friday 1:00 PM meetings going forward",
          "Tiffany: Consider signing up for Master Class for Teaching (June or September sessions)"
        ]
      },
      "lastActiveDate": "2026-04-23",
      "lastActive": "7 days ago",
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 30",
        "text": "[ ] AI Task Force [ ] EDL AI Task Force [ ] BST [ ] ITAC [ ] TPH [ ] CHS General [x] POP [ ] LSC / STP [ ] MNS [ ] Program Transitioning [ ] Other: **People** (check all present): [x] Other: Tiffany Lemon [ ] Amanda Gulley [ ] Auryan Ratliff [ ] Bernard Johnson Jr [ ] Brent Espineda [ ] Dariush Navabi [ ] Habte Tadesse [ ] Lauren Sosa Leo [ ] Matthew Robinson [ ] Michael Arseneault [ ] Michael Duah [ ] Michael Miller [ ] Patrick White [ ] Rockell Schmidt [ ] Ron Carranza [ ] Tamara Mitchell [ ] Wayne Anderson [ ] Wesley Fleming [ ] Yunro Chung [ ] Rache Gur-Arie [ ] Josh Louchman [ ] Josh Anbar [x] Tiffany Lemon **Follow-up Meeting Scheduled For**:",
        "source": "granola"
      }
    },
    "chs100": {
      "calendarMeetings": [
        {
          "date": "2026-05-13",
          "time": "2:00 PM",
          "label": "CHS Redesign - Project Onboarding",
          "uid": "040000008200E00074C5B7101A82E00800000000DA575ED0C8E1DC01000000000000000010000000361E4B4A4B60AD4E97EB25CE0023944F",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-13T21:00:00.000Z",
          "dtEndIso": "2026-05-13T22:00:00.000Z"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-13",
        "time": "2:00 PM",
        "label": "CHS Redesign - Project Onboarding"
      }
    },
    "chs300": {
      "calendarMeetings": [
        {
          "date": "2026-05-13",
          "time": "2:00 PM",
          "label": "CHS Redesign - Project Onboarding",
          "uid": "040000008200E00074C5B7101A82E00800000000DA575ED0C8E1DC01000000000000000010000000361E4B4A4B60AD4E97EB25CE0023944F",
          "durationMinutes": 60,
          "past": false,
          "dtStartIso": "2026-05-13T21:00:00.000Z",
          "dtEndIso": "2026-05-13T22:00:00.000Z"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-13",
        "time": "2:00 PM",
        "label": "CHS Redesign - Project Onboarding"
      }
    }
  },
  "upcomingDeadlines": [
    {
      "date": "2026-05-12",
      "month": "May",
      "day": "12",
      "title": "CLOs and ELOs Due",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "urgent": true,
      "hasMeeting": true,
      "meetingTime": "1:30 PM",
      "meetingLabel": "BST 605 Lecture Planning"
    },
    {
      "date": "2026-05-13",
      "month": "May",
      "day": "13",
      "title": "Materials Review (2:00 PM)",
      "course": "MNS 521 — AI Technologies (Navabi)",
      "hasMeeting": true,
      "meetingTime": "2:30 PM",
      "meetingLabel": "MNS 521 - Module 2",
      "urgent": true
    },
    {
      "date": "2026-07-20",
      "month": "Jul",
      "day": "20",
      "title": "Course Shell Due",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "hasMeeting": false
    },
    {
      "date": "2026-08-01",
      "month": "Aug",
      "day": "1",
      "title": "Final Walkthrough & QA",
      "course": "MNS 521 — AI Technologies (Navabi)",
      "hasMeeting": false
    },
    {
      "date": "2026-08-17",
      "month": "Aug",
      "day": "17",
      "title": "Student Access / Launch",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "hasMeeting": false
    },
    {
      "date": "2026-09-14",
      "month": "Sep",
      "day": "14",
      "title": "QA Deadline",
      "course": "BST 606 — Applied Clinical Trial Design (Yunro Chung)",
      "hasMeeting": false
    },
    {
      "date": "2026-10-14",
      "month": "Oct",
      "day": "14",
      "title": "Session B Launch",
      "course": "BST 606 — Applied Clinical Trial Design (Yunro Chung)",
      "hasMeeting": false
    }
  ],
  "calendarSyncedAt": "2026-05-12T16:52:39.471Z",
  "notesSyncedAt": "2026-05-12T16:52:39.471Z"
};
