// Auto-generated by sync-calendar.js from Outlook + Obsidian
// Last synced: 2026-04-10T21:19:31.061Z
window.SYNCED_DATA = {
  "syncedAt": "2026-04-10T21:19:31.061Z",
  "source": "outlook+obsidian",
  "courses": {
    "mns521": {
      "lastActiveDate": "2026-04-02",
      "lastActive": "8 days ago",
      "actionItems": {
        "total": 16,
        "done": 0,
        "pending": [
          "Dariush: add point distribution to all assignments",
          "Dariush: write out full assignment details — keep \"which assignment will students be most excited about?\" in mind",
          "Dariush: list materials for each module (textbook chapters, slides, lecture videos ~5–10 min each, supplementary readings, software/tools)",
          "Dariush: consider tool-oriented assignments (e.g., Jupyter Notebook install + basic use) that blend learning material into the assignment",
          "Elisa: set up Zoom link for next meeting (April 17, 2:00 PM) — materials review only",
          "Elisa: use date-push tool (per Tamara) to populate all assignment due dates from March 18 baseline, Thursdays",
          "Elisa investigate Harmonize grade export functionality and integration options",
          "Research API token access and configuration for Harmonize integration",
          "Dariush to complete assignment planning table by March 30, 2026",
          "Schedule follow-up meeting for April 2, 2026 at 1:00 PM",
          "Create sample Module 1 assignment drafts before next Thursday meeting",
          "Elisa create sample Module 1 assignment drafts before Thursday",
          "Dariush provide faculty feedback on sample assignments",
          "Differentiate CLOs and ELOs by module to show progression",
          "Continue iterative assignment refinement process",
          "Test assignment formats in Canvas and/or Articulate Rise"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 10",
        "text": "Pending: add point distribution to all assignments; write out full assignment details — keep \"which assignment w; list materials for each module (textbook chapters, slides, l. Recent decisions: All assignments due on Thursdays; Spring B 2027 baseline: March 18 = first due date.",
        "source": "obsidian"
      },
      "nextMeeting": {
        "date": "2026-04-16",
        "time": "2:00 PM",
        "label": "MNS 521 Materials Review"
      },
      "milestoneStatus": [
        {
          "status": "done"
        },
        {
          "status": "done"
        },
        {
          "status": "done"
        },
        {
          "status": "meeting",
          "meetingDate": "2026-04-16",
          "meetingLabel": "Apr 16 at 2:00 PM"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Apr 17",
          "label": "Materials Review (2:00 PM)",
          "statusText": "14 days away"
        },
        {
          "date": "Aug 1",
          "label": "Final Walkthrough & QA",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Apr 2, 2026",
          "title": "MNS 521 Assignments Review",
          "people": [
            "Elisa Penmar",
            "Dariush"
          ],
          "summary": "- CLO #3 was missing — placeholder text removed, restored to: \"Recognize the mechanics of machine learning algorithms\" - \"Understand\" flagged as non-assessable verb in one ELO → replaced with \"explain\" (e.g., \"explain the evolution of…\") - Module objectives map to ELOs, not CLOs — but keeping CLOs clean still worthwhile - Module 6 (AI Architecture Proposal draft) feeds directly into Module 7 (final project) - Modules 2 and 4 have 4 assignments; all others have 3 — workload expected approximately",
          "decisions": [
            "All assignments due on Thursdays",
            "Spring B 2027 baseline: March 18 = first due date",
            "Harmonize auto-grading with 80/20 split (initial post / peer responses)",
            "MNS 522 = no new development needed (existing ACO 580 course)"
          ],
          "actionItems": [
            {
              "text": "Dariush: add point distribution to all assignments",
              "done": false
            },
            {
              "text": "Dariush: write out full assignment details — keep \"which assignment will students be most excited about?\" in mind",
              "done": false
            },
            {
              "text": "Dariush: list materials for each module (textbook chapters, slides, lecture videos ~5–10 min each, supplementary readings, software/tools)",
              "done": false
            },
            {
              "text": "Dariush: consider tool-oriented assignments (e.g., Jupyter Notebook install + basic use) that blend learning material into the assignment",
              "done": false
            },
            {
              "text": "Elisa: set up Zoom link for next meeting (April 17, 2:00 PM) — materials review only",
              "done": false
            },
            {
              "text": "Elisa: use date-push tool (per Tamara) to populate all assignment due dates from March 18 baseline, Thursdays",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 19, 2026",
          "title": "First Solo Meeting with Dariush",
          "people": [
            "Elisa Penmar",
            "Dariush"
          ],
          "summary": "**Decision Made**: Harmonize chosen over YellowDig for collaborative work **Reasoning**: - Better support for collaborative learning activities - More flexible assessment options - Superior grade management capabilities - Alignment with ASU Online standards Designing interactive assignment using agent models: - **Concept**: Students engage with AI agent scenarios",
          "decisions": [
            "Use Harmonize platform for assignments and collaboration",
            "Implement agent model exercise with differentiated tracks",
            "Use scenario-based assignment approach",
            "Support both in-person and online course modalities"
          ],
          "actionItems": [
            {
              "text": "Elisa investigate Harmonize grade export functionality and integration options",
              "done": false
            },
            {
              "text": "Research API token access and configuration for Harmonize integration",
              "done": false
            },
            {
              "text": "Dariush to complete assignment planning table by March 30, 2026",
              "done": false
            },
            {
              "text": "Schedule follow-up meeting for April 2, 2026 at 1:00 PM",
              "done": false
            },
            {
              "text": "Create sample Module 1 assignment drafts before next Thursday meeting",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 13, 2026",
          "title": "MNS 521 Meeting",
          "people": [
            "Elisa Penmar",
            "Dariush"
          ],
          "summary": "**Status**: 7 Course Learning Outcomes defined for MNS 521 - CLOs cover AI and intelligent agents course scope - Comprehensive coverage of learning objectives **Issue Identified**: Module objectives incorrectly identical - **Problem**: Each module's enabling learning outcomes are the same - **Root Cause**: Copy-paste error or incomplete differentiation - **Solution Needed**: Unique, progressive ELOs for each module - **Impact**: Students won't understand progression or mastery levels",
          "decisions": [
            "Use collaborative iterative design approach for assignments",
            "Explore multiple assignment formats (quizzes, interactive, scenarios)",
            "Focus on meaningful distinctions between AI and traditional software",
            "Plan for in-person and online delivery flexibility"
          ],
          "actionItems": [
            {
              "text": "Elisa create sample Module 1 assignment drafts before Thursday",
              "done": false
            },
            {
              "text": "Dariush provide faculty feedback on sample assignments",
              "done": false
            },
            {
              "text": "Differentiate CLOs and ELOs by module to show progression",
              "done": false
            },
            {
              "text": "Continue iterative assignment refinement process",
              "done": false
            },
            {
              "text": "Test assignment formats in Canvas and/or Articulate Rise",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-04-16",
          "time": "2:00 PM",
          "label": "MNS 521 Materials Review",
          "uid": "040000008200E00074C5B7101A82E008000000007F47C1C8F0C2DC010000000000000000100000003BE198968CBCAF4D9F0ACCA85A3E5C39"
        }
      ]
    },
    "bst605": {
      "lastActiveDate": "2026-04-10",
      "lastActive": "Today",
      "actionItems": {
        "total": 17,
        "done": 0,
        "pending": [
          "Send Habte email invitation to course development platform (BST 605 + BST 609 links)",
          "Habte: review and update module-level objectives and ELO tags in platform",
          "Habte: determine assignment weights",
          "Habte: list all assignments for each module before April 24th meeting",
          "Add assignment weights section to course info page in platform",
          "Fix platform bugs: ELO tagging not saving, comment display not loading, data loss on input",
          "Follow up on Canvas quiz issue (unresolved from previous discussions)",
          "Schedule Friday meeting to prepare for hack day activities",
          "Test YellowDig functionality for assignment platform consideration",
          "Coordinate Harmonize integration and grade export options",
          "Course planning worksheet completed by April 27, 2026",
          "Course learning outcomes (CLOs) defined by April 6, 2026",
          "Enabling learning outcomes (ELOs) defined by April 6, 2026",
          "Tamara's transcript reviewed as facilitator notes",
          "Research LaTeX software options for math content rendering",
          "Create kickoff meeting guide from Tamara's planning questions",
          "Module 0 (math refresher) content framework developed"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 10",
        "text": "Pending: Send Habte email invitation to course development platform (; review and update module-level objectives and ELO tags in pl; determine assignment weights. Recent decisions: BST 605 converting from 15-week in-person to 7.5-week online intensive (7 modules + Module 0); Midterm exam placed at end of Module 3.",
        "source": "obsidian"
      },
      "nextMeeting": {
        "date": "2026-04-10",
        "time": "8:00 AM",
        "label": "BST 605 - CLOs and ELOs"
      },
      "milestoneStatus": [
        {
          "status": "meeting",
          "meetingDate": "2026-04-10",
          "meetingLabel": "Apr 10 at 8:00 AM"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Apr 6",
          "label": "CLOs and ELOs Due",
          "urgent": true,
          "statusText": "3 days away"
        },
        {
          "date": "Jul 20",
          "label": "Course Shell Due",
          "bold": true
        },
        {
          "date": "Aug 17",
          "label": "Student Access / Launch",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Apr 10, 2026",
          "title": "BST 605 - CLOs and ELOs",
          "people": [
            "Habte"
          ],
          "summary": "- Testing new web-based course development application to replace Google Doc worksheets - Platform includes automatic timeline generation, ELO/CLO alignment tools, and syllabus generation features - Final walkthrough date auto-populated as July 20th (4 weeks before fall launch) - Habte will receive email invitation to test the platform and provide feedback - Converting BST 605 from 15-week in-person format to 7.5-week online intensive - Online students expected to complete 13–17 hours of coursew",
          "decisions": [
            "BST 605 converting from 15-week in-person to 7.5-week online intensive (7 modules + Module 0)",
            "Midterm exam placed at end of Module 3",
            "Linear mixed models included in Module 7 (repeated measures)",
            "BST 609 (Fall B) to be developed in parallel"
          ],
          "actionItems": [
            {
              "text": "Send Habte email invitation to course development platform (BST 605 + BST 609 links)",
              "done": false
            },
            {
              "text": "Habte: review and update module-level objectives and ELO tags in platform",
              "done": false
            },
            {
              "text": "Habte: determine assignment weights",
              "done": false
            },
            {
              "text": "Habte: list all assignments for each module before April 24th meeting",
              "done": false
            },
            {
              "text": "Add assignment weights section to course info page in platform",
              "done": false
            },
            {
              "text": "Fix platform bugs: ELO tagging not saving, comment display not loading, data loss on input",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 20, 2026",
          "title": "Tamara Check-In",
          "people": [
            "Elisa Penmar",
            "Tamara Mitchell"
          ],
          "summary": "Discussion of how to structure and facilitate kickoff meetings with faculty new to online course design: - Balancing faculty concerns with instructional design expertise - Managing varying levels of faculty preparation and readiness - Using backstory and context setting for new faculty - Collaborative versus directive facilitation approaches - Reviewing kickoff meeting facilitation approach - Faculty (Habte) readiness assessment and support needed - Statistical course content considerations",
          "decisions": [
            "Implement daily FYI app check as new communication protocol",
            "Proceed with Sentana Canvas integration",
            "Continue PDF remediation tool development",
            "Advance Canvas Skills package consolidation"
          ],
          "actionItems": [
            {
              "text": "Follow up on Canvas quiz issue (unresolved from previous discussions)",
              "done": false
            },
            {
              "text": "Schedule Friday meeting to prepare for hack day activities",
              "done": false
            },
            {
              "text": "Test YellowDig functionality for assignment platform consideration",
              "done": false
            },
            {
              "text": "Coordinate Harmonize integration and grade export options",
              "done": false
            }
          ],
          "source": "Obsidian"
        },
        {
          "date": "Mar 20, 2026",
          "title": "BST 605 Course Kick-Off",
          "people": [
            "Elisa Penmar",
            "Tamara Mitchell",
            "Habte"
          ],
          "summary": "- **Course Code**: BST 605 - **Title**: Statistical Principles of Clinical Trials - **Format**: Online (converting from in-person) - **Target Launch**: Fall 2026 (Fall A semester) - **Faculty Lead**: Habte (experienced instructor) - **Course Shell Due**: July 20, 2026 - **Student Access**: August 17, 2026 - **CLOs/ELOs Due**: April 6, 2026",
          "decisions": [
            "Use backwards design methodology for course development",
            "Implement multiple assessment formats (assignments, homework, exams, projects)",
            "Create math refresher module for student support",
            "Follow ASU Online course shell requirements (due July 20)",
            "Establish April 6 as interim checkpoint for CLOs/ELOs definition"
          ],
          "actionItems": [
            {
              "text": "Course planning worksheet completed by April 27, 2026",
              "done": false
            },
            {
              "text": "Course learning outcomes (CLOs) defined by April 6, 2026",
              "done": false
            },
            {
              "text": "Enabling learning outcomes (ELOs) defined by April 6, 2026",
              "done": false
            },
            {
              "text": "Tamara's transcript reviewed as facilitator notes",
              "done": false
            },
            {
              "text": "Research LaTeX software options for math content rendering",
              "done": false
            },
            {
              "text": "Create kickoff meeting guide from Tamara's planning questions",
              "done": false
            },
            {
              "text": "Module 0 (math refresher) content framework developed",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-04-10",
          "time": "1:00 AM",
          "label": "60-min Meeting - Habte Tadesse LIKASSA",
          "uid": "040000008200E00074C5B7101A82E00800000000B48AAF380DC6DC0100000000000000001000000063657800CFCA0245B8763307F05AFBBF"
        },
        {
          "date": "2026-04-10",
          "time": "8:00 AM",
          "label": "BST 605 - CLOs and ELOs",
          "uid": "040000008200E00074C5B7101A82E00800000000191097E09FC6DC010000000000000000100000002860E4E88F690947BD448FAA4D0FCCE5"
        },
        {
          "date": "2026-04-24",
          "time": "8:00 AM",
          "label": "BST 605 Assignment Review ",
          "uid": "040000008200E00074C5B7101A82E008000000008B9D911901C9DC010000000000000000100000001509B2ECA82B724C989D941C3F6E1111"
        }
      ]
    },
    "bst606": {
      "lastActiveDate": "2026-03-30",
      "lastActive": "11 days ago",
      "actionItems": {
        "total": 4,
        "done": 0,
        "pending": [
          "Send Google Drive access, slideshow, and course development worksheet via email (Elisa)",
          "Faculty complete ELOs and CLOs independently",
          "Review submitted ELOs/CLOs",
          "Explore MasterClass workshop for Yunro (quarterly availability)"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 10",
        "text": "Pending: Send Google Drive access, slideshow, and course development ; Faculty complete ELOs and CLOs independently; Review submitted ELOs/CLOs. Recent decisions: Communication primarily via email unless meetings needed for complex items; Backward design approach for course development.",
        "source": "obsidian"
      },
      "nextMeeting": null,
      "milestoneStatus": [
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Sep 14",
          "label": "QA Deadline",
          "bold": true
        },
        {
          "date": "Oct 14",
          "label": "Session B Launch — Student Access",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Mar 30, 2026",
          "title": "BST 606 Yunro Chung Kickoff",
          "people": [
            "Elisa Penmar",
            "Yunro Chung"
          ],
          "summary": "- ASU Digital Learning provides collaborative partnership throughout entire process - Support continues after course launch, not just pre-launch - Quality assurance embedded throughout - Four key support areas: instructional designers, academic media team, learning technologies, faculty support group - Backward design methodology: objectives → assessments → learning materials - Course must be ready 4 weeks before launch for QA review - Fall Session B starts October 14, 2026 — QA deadline Septemb",
          "decisions": [
            "Communication primarily via email unless meetings needed for complex items",
            "Backward design approach for course development",
            "Shared Google Drive for collaboration"
          ],
          "actionItems": [
            {
              "text": "Send Google Drive access, slideshow, and course development worksheet via email (Elisa)",
              "done": false
            },
            {
              "text": "Faculty complete ELOs and CLOs independently",
              "done": false
            },
            {
              "text": "Review submitted ELOs/CLOs",
              "done": false
            },
            {
              "text": "Explore MasterClass workshop for Yunro (quarterly availability)",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-04-06",
          "time": "8:30 AM",
          "label": "Send email follow up for BST 606",
          "uid": "040000008200E00074C5B7101A82E00800000000CA5923B5DCC2DC010000000000000000100000002404B511998B3B4E962598059F9602C4"
        }
      ]
    },
    "tph552": {
      "lastActiveDate": "2026-04-02",
      "lastActive": "8 days ago",
      "actionItems": {
        "total": 4,
        "done": 0,
        "pending": [
          "Vienna: confirm with Ina that she's comfortable with the collapsed objectives structure",
          "Vienna: clean up and finalize the course map at next meeting",
          "Vienna: resolve notes column in the mapping document",
          "Elisa: continue development of assignments overview and materials overview pages (drag-between-modules feature in progress)"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 10",
        "text": "Pending: confirm with Ina that she's comfortable with the collapsed o; clean up and finalize the course map at next meeting; resolve notes column in the mapping document. Recent decisions: Designing as 7.5-week course (condensed from 15-week in-person); Module 12 assignments become Module 7 in new structure.",
        "source": "obsidian"
      },
      "nextMeeting": null,
      "milestoneStatus": [],
      "milestones": [],
      "meetings": [
        {
          "date": "Apr 2, 2026",
          "title": "TPH 552",
          "people": [
            "Elisa Penmar"
          ],
          "summary": "- Vienna teaching existing in-person version; now designing the in-person/online course - Not due until Summer 2027 — she's starting early - SAFE-aligned course; existing 15-week model being redesigned as 7.5-week course - Course map reviewed and approved by Ina and the program lead - Remaining step: confirm Ina is comfortable with how objectives were collapsed - Everything maps to ELOs, not CLOs — CLOs are essentially a list of topics being taught - ELOs = what students must do; CLOs = what nee",
          "decisions": [
            "Designing as 7.5-week course (condensed from 15-week in-person)",
            "Module 12 assignments become Module 7 in new structure"
          ],
          "actionItems": [
            {
              "text": "Vienna: confirm with Ina that she's comfortable with the collapsed objectives structure",
              "done": false
            },
            {
              "text": "Vienna: clean up and finalize the course map at next meeting",
              "done": false
            },
            {
              "text": "Vienna: resolve notes column in the mapping document",
              "done": false
            },
            {
              "text": "Elisa: continue development of assignments overview and materials overview pages (drag-between-modules feature in progress)",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ]
    },
    "tph557": {
      "calendarMeetings": [
        {
          "date": "2026-04-23",
          "time": "11:00 AM",
          "label": "TPH 557 - Module Objective Allignment",
          "uid": "040000008200E00074C5B7101A82E008000000000006834CD2C6DC010000000000000000100000007E46AADE2426A543A82A1A698CDDF3C3"
        }
      ],
      "nextMeeting": {
        "date": "2026-04-23",
        "time": "11:00 AM",
        "label": "TPH 557 - Module Objective Allignment"
      },
      "meetings": [
        {
          "date": "Apr 7, 2026",
          "title": "TPH 557 Course Development Kickoff",
          "people": [
            "Elisa Penmar",
            "Tamara Mitchell",
            "Rachel Gur-Arie"
          ],
          "summary": "- **Course Code**: TPH 557 - **Title**: PH Tech Ethics, Policy and Law - **Format**: Online (converting from in-person) - **Target Launch**: Fall 2026 (need confirmation if Fall A or Fall B) - **Faculty Lead**: Rachel Gur-Arie - **Structure**: 7-week accelerated format (up to 18 hours/week) - Previously taught HCR 210 online ethics for nursing college - Split 50% appointment between FCPH and nursing college",
          "decisions": [
            "Use backwards design methodology for course development",
            "Implement video-based discussions via Flipgrid/Harmonize",
            "Explore podcast format for each module",
            "Plan media production early for fall timeline"
          ],
          "actionItems": [
            {
              "text": "Rachel: complete course development worksheet",
              "done": false
            },
            {
              "text": "Rachel: include enrollment caps information",
              "done": false
            },
            {
              "text": "Rachel: map topics for 7-module structure and define module objectives",
              "done": false
            },
            {
              "text": "Clarify accreditation-required assignments with program",
              "done": false
            },
            {
              "text": "Resolve teaching assignment conflict between colleges",
              "done": false
            },
            {
              "text": "Confirm if Fall A or Fall B launch",
              "done": false
            },
            {
              "text": "Schedule media planning early for fall production timeline",
              "done": false
            }
          ],
          "source": "Obsidian"
        }
      ],
      "actionItems": {
        "total": 7,
        "done": 0,
        "pending": [
          "Rachel: complete course development worksheet",
          "Rachel: include enrollment caps information",
          "Rachel: map topics for 7-module structure and define module objectives",
          "Clarify accreditation-required assignments with program",
          "Resolve teaching assignment conflict between colleges",
          "Confirm if Fall A or Fall B launch",
          "Schedule media planning early for fall production timeline"
        ]
      },
      "lastActiveDate": "2026-04-07",
      "lastActive": "3 days ago",
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 10",
        "text": "Pending: complete course development worksheet; include enrollment caps information; map topics for 7-module structure and define module objectiv. Recent decisions: Use backwards design methodology for course development; Implement video-based discussions via Flipgrid/Harmonize.",
        "source": "obsidian"
      }
    },
    "tph550": {
      "calendarMeetings": [
        {
          "date": "2026-04-20",
          "time": "2:00 PM",
          "label": "TPH 550 Devo Meeting",
          "uid": "040000008200E00074C5B7101A82E0080000000028CB520511C6DC01000000000000000010000000C8667B0A1A520342BBC8CA1F6F20406E"
        }
      ],
      "nextMeeting": {
        "date": "2026-04-20",
        "time": "2:00 PM",
        "label": "TPH 550 Devo Meeting"
      }
    }
  },
  "upcomingDeadlines": [
    {
      "date": "2026-04-10",
      "month": "Apr",
      "day": "10",
      "title": "CLOs and ELOs Due",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "urgent": true,
      "hasMeeting": true,
      "meetingTime": "1:00 AM",
      "meetingLabel": "60-min Meeting - Habte Tadesse LIKASSA"
    },
    {
      "date": "2026-04-17",
      "month": "Apr",
      "day": "17",
      "title": "Materials Review (2:00 PM)",
      "course": "MNS 521 — AI Technologies (Navabi)",
      "hasMeeting": true,
      "meetingTime": "2:00 PM",
      "meetingLabel": "MNS 521 Materials Review"
    },
    {
      "date": "2026-07-20",
      "month": "Jul",
      "day": "20",
      "title": "Course Shell Due",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "hasMeeting": false
    },
    {
      "date": "2026-08-01",
      "month": "Aug",
      "day": "1",
      "title": "Final Walkthrough & QA",
      "course": "MNS 521 — AI Technologies (Navabi)",
      "hasMeeting": false
    },
    {
      "date": "2026-08-17",
      "month": "Aug",
      "day": "17",
      "title": "Student Access / Launch",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "hasMeeting": false
    },
    {
      "date": "2026-09-14",
      "month": "Sep",
      "day": "14",
      "title": "QA Deadline",
      "course": "BST 606 — Applied Clinical Trial Design (Yunro Chung)",
      "hasMeeting": false
    },
    {
      "date": "2026-10-14",
      "month": "Oct",
      "day": "14",
      "title": "Session B Launch",
      "course": "BST 606 — Applied Clinical Trial Design (Yunro Chung)",
      "hasMeeting": false
    }
  ],
  "calendarSyncedAt": "2026-04-10T21:19:31.061Z",
  "notesSyncedAt": "2026-04-10T21:19:31.061Z"
};
