// Auto-generated by sync-granola.mjs (Granola public API)
// Last synced: 2026-04-18T18:27:28.877Z
window.SYNCED_DATA = {
  "syncedAt": "2026-04-18T18:27:28.877Z",
  "source": "outlook+granola",
  "courses": {
    "mns521": {
      "lastActiveDate": "2026-04-16",
      "lastActive": "2 days ago",
      "actionItems": {
        "total": 24,
        "done": 0,
        "pending": [
          "Elisa will enter all Module 2 materials into development platform",
          "Instructor will review and approve MLO alignments via email or working meeting",
          "Development of Module 1 materials for April 27th delivery",
          "Creation of ACO 501 development shell with accessibility improvements",
          "Continued testing and bug fixes for collaborative platform features",
          "Darush: Add point distribution to all assignments",
          "Darush: Write out full assignment details — keep “which assignment will students be most excited about?” in mind",
          "Darush: List materials for each module (textbook chapters, slides, lecture videos \\~5–10 min each, supplementary readings, software/tools)",
          "Darush: Consider tool-oriented assignments (e.g., Jupyter Notebook install + basic use) that blend learning material into the assignment",
          "Elisa: Set up Zoom link for next meeting (April 17, 2:00 PM) — materials review only",
          "Elisa: Use date-push tool (per Tamara) to populate all assignment due dates from March 18 baseline, Thursdays",
          "Next meeting: **Thursday, April 17 at 2:00 PM** — Materials review (module-by-module)",
          "**Elisa Penmar**: Create sample drafts for Module 1 assignments before Thursday meeting",
          "AI misconceptions debate (YellowDig discussion format)",
          "AI modeling exercise (written assignment)",
          "Assignment: What distinguishes AI from traditional software (could be written assignment or quiz with matching)",
          "**Faculty member**: Complete assignment planning and incorporate creative ideas discussed",
          "Consider hands-on, practical approaches over purely conceptual assignments",
          "Think about constraint satisfaction problem for Module 2 mini design task",
          "Explore presentation and multimedia options for student submissions",
          "**Both parties**: Continue iterative collaborative process for remaining modules",
          "Focus on appealing to different learning styles and AI experience levels",
          "Balance creativity with appropriate constraints",
          "Maintain efficiency in course delivery while challenging students without confusion"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 18",
        "text": "Course structure will emphasize big picture understanding over detailed PowerPoint discussions. Recording strategy will be selective",
        "source": "granola"
      },
      "nextMeeting": {
        "date": "2026-04-30",
        "time": "1:30 PM",
        "label": "MNS 521 - Module 1"
      },
      "milestoneStatus": [
        {
          "status": "done"
        },
        {
          "status": "done"
        },
        {
          "status": "done"
        },
        {
          "status": "meeting",
          "meetingDate": "2026-04-30",
          "meetingLabel": "Apr 30 at 1:30 PM"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Apr 17",
          "label": "Materials Review (2:00 PM)",
          "statusText": "14 days away"
        },
        {
          "date": "Aug 1",
          "label": "Final Walkthrough & QA",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Apr 16, 2026",
          "title": "MNS 521 - Materials",
          "people": [
            "Dariush Navabi"
          ],
          "summary": "Course structure will emphasize big picture understanding over detailed PowerPoint discussions. Recording strategy will be selective",
          "decisions": [],
          "actionItems": [
            {
              "text": "Elisa will enter all Module 2 materials into development platform",
              "done": false
            },
            {
              "text": "Instructor will review and approve MLO alignments via email or working meeting",
              "done": false
            },
            {
              "text": "Development of Module 1 materials for April 27th delivery",
              "done": false
            },
            {
              "text": "Creation of ACO 501 development shell with accessibility improvements",
              "done": false
            },
            {
              "text": "Continued testing and bug fixes for collaborative platform features",
              "done": false
            }
          ],
          "granola": "https://notes.granola.ai/d/210deec7-8b99-4eb9-882f-3f3e90c305a6",
          "transcriptUrl": "https://notes.granola.ai/t/055acb36-7041-4bea-a7ac-126a7b01703f",
          "source": "Granola"
        },
        {
          "date": "Apr 2, 2026",
          "title": "MNS 521 Assignments Review",
          "people": [
            "Elisa Penmar"
          ],
          "summary": "CLO #3 was missing — placeholder text removed, restored to: “Recognize the mechanics of machine learning algorithms”. “Understand” flagged as non-assessable verb in one ELO → replaced with “explain” (e.g., “explain the evolution of…”)",
          "decisions": [],
          "actionItems": [
            {
              "text": "Darush: Add point distribution to all assignments",
              "done": false
            },
            {
              "text": "Darush: Write out full assignment details — keep “which assignment will students be most excited about?” in mind",
              "done": false
            },
            {
              "text": "Darush: List materials for each module (textbook chapters, slides, lecture videos \\~5–10 min each, supplementary readings, software/tools)",
              "done": false
            },
            {
              "text": "Darush: Consider tool-oriented assignments (e.g., Jupyter Notebook install + basic use) that blend learning material into the assignment",
              "done": false
            },
            {
              "text": "Elisa: Set up Zoom link for next meeting (April 17, 2:00 PM) — materials review only",
              "done": false
            },
            {
              "text": "Elisa: Use date-push tool (per Tamara) to populate all assignment due dates from March 18 baseline, Thursdays",
              "done": false
            },
            {
              "text": "Next meeting: **Thursday, April 17 at 2:00 PM** — Materials review (module-by-module)",
              "done": false
            }
          ],
          "granola": "https://notes.granola.ai/d/3b6b21fe-66e6-4999-ba3f-0ead67543f88",
          "transcriptUrl": "https://notes.granola.ai/t/8746cc37-3128-4906-80aa-e9709b7c85ef",
          "source": "Granola"
        },
        {
          "date": "Mar 13, 2026",
          "title": "MNS 521 Meeting on 3.13",
          "people": [
            "Elisa Penmar"
          ],
          "summary": "No significant professional or company-wide announcements were made during this meeting. Meeting began with brief departure of another participant who had a scheduling conflict with a Thursday meeting",
          "decisions": [],
          "actionItems": [
            {
              "text": "**Elisa Penmar**: Create sample drafts for Module 1 assignments before Thursday meeting",
              "done": false
            },
            {
              "text": "AI misconceptions debate (YellowDig discussion format)",
              "done": false
            },
            {
              "text": "AI modeling exercise (written assignment)",
              "done": false
            },
            {
              "text": "Assignment: What distinguishes AI from traditional software (could be written assignment or quiz with matching)",
              "done": false
            },
            {
              "text": "**Faculty member**: Complete assignment planning and incorporate creative ideas discussed",
              "done": false
            },
            {
              "text": "Consider hands-on, practical approaches over purely conceptual assignments",
              "done": false
            },
            {
              "text": "Think about constraint satisfaction problem for Module 2 mini design task",
              "done": false
            },
            {
              "text": "Explore presentation and multimedia options for student submissions",
              "done": false
            },
            {
              "text": "**Both parties**: Continue iterative collaborative process for remaining modules",
              "done": false
            },
            {
              "text": "Focus on appealing to different learning styles and AI experience levels",
              "done": false
            },
            {
              "text": "Balance creativity with appropriate constraints",
              "done": false
            },
            {
              "text": "Maintain efficiency in course delivery while challenging students without confusion",
              "done": false
            }
          ],
          "granola": "https://notes.granola.ai/d/f8896ffa-8387-4d4c-b271-4ddb7bd761b7",
          "transcriptUrl": "https://notes.granola.ai/t/f163304f-3f05-4a4b-af43-e09e8866268d",
          "source": "Granola"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-04-30",
          "time": "1:30 PM",
          "label": "MNS 521 - Module 1",
          "uid": "040000008200E00074C5B7101A82E00800000000B6661353E7CDDC01000000000000000010000000089722CF9CC5464F8763AD1403CE66E0"
        }
      ]
    },
    "bst605": {
      "lastActiveDate": "2026-04-10",
      "lastActive": "8 days ago",
      "actionItems": {
        "total": 0,
        "done": 0,
        "pending": []
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 18",
        "text": "Testing new web-based course development application to replace Google Doc worksheets. Platform includes automatic timeline generation, ELO/CLO alignment tools, and syllabus generation features",
        "source": "granola"
      },
      "nextMeeting": {
        "date": "2026-04-24",
        "time": "8:00 AM",
        "label": "BST 605 Assignment Review "
      },
      "milestoneStatus": [
        {
          "status": "meeting",
          "meetingDate": "2026-04-24",
          "meetingLabel": "Apr 24 at 8:00 AM"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Apr 6",
          "label": "CLOs and ELOs Due",
          "urgent": true,
          "statusText": "3 days away"
        },
        {
          "date": "Jul 20",
          "label": "Course Shell Due",
          "bold": true
        },
        {
          "date": "Aug 17",
          "label": "Student Access / Launch",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Apr 10, 2026",
          "title": "BST 605 - CLOs and ELOs",
          "people": [
            "Habte Tadesse"
          ],
          "summary": "Testing new web-based course development application to replace Google Doc worksheets. Platform includes automatic timeline generation, ELO/CLO alignment tools, and syllabus generation features",
          "decisions": [],
          "actionItems": [],
          "granola": "https://notes.granola.ai/d/b3e94a95-0645-4cff-968d-c1a55b341ba0",
          "transcriptUrl": "https://notes.granola.ai/t/0d40057a-34d9-43dc-95ef-c06c7d51589e",
          "source": "Granola"
        },
        {
          "date": "Mar 20, 2026",
          "title": "BST 605 Course Kick-Off",
          "people": [
            "Habte Tadesse",
            "Tamara Mitchell"
          ],
          "summary": "BST 605 Fall 2026 (A course) launching on August 20th. Course currently taught in-person by Professor Habte Tadesse (first name confirmed)",
          "decisions": [],
          "actionItems": [],
          "granola": "https://notes.granola.ai/d/b8fa5e29-c8b1-454b-85be-8c75dcfe9c4e",
          "transcriptUrl": "https://notes.granola.ai/t/faf6b6f5-9826-40b9-bd0f-e3bae5f45990",
          "source": "Granola"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-04-24",
          "time": "8:00 AM",
          "label": "BST 605 Assignment Review ",
          "uid": "040000008200E00074C5B7101A82E008000000008B9D911901C9DC010000000000000000100000001509B2ECA82B724C989D941C3F6E1111"
        }
      ]
    },
    "bst606": {
      "lastActiveDate": "2026-03-30",
      "lastActive": "19 days ago",
      "actionItems": {
        "total": 4,
        "done": 0,
        "pending": [
          "Elisa to send Google Drive access, slideshow, and course development worksheet via email",
          "Faculty will complete ELOs/CLOs independently and submit for review",
          "Communication via email unless meeting needed for complex items",
          "MasterClass workshop available (4x yearly) for online teaching experience and networking"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 18",
        "text": "ASU Digital Learning (EDL) supports online course design, development and delivery across university. Team provides academic support beyond tech support - collaborative partnership throughout process",
        "source": "granola"
      },
      "nextMeeting": null,
      "milestoneStatus": [
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        },
        {
          "status": "pending"
        }
      ],
      "milestones": [
        {
          "date": "Sep 14",
          "label": "QA Deadline",
          "bold": true
        },
        {
          "date": "Oct 14",
          "label": "Session B Launch — Student Access",
          "bold": true
        }
      ],
      "meetings": [
        {
          "date": "Mar 30, 2026",
          "title": "BST 606 Yunro Chung Kickoff",
          "people": [
            "Elisa Penmar"
          ],
          "summary": "ASU Digital Learning (EDL) supports online course design, development and delivery across university. Team provides academic support beyond tech support - collaborative partnership throughout process",
          "decisions": [],
          "actionItems": [
            {
              "text": "Elisa to send Google Drive access, slideshow, and course development worksheet via email",
              "done": false
            },
            {
              "text": "Faculty will complete ELOs/CLOs independently and submit for review",
              "done": false
            },
            {
              "text": "Communication via email unless meeting needed for complex items",
              "done": false
            },
            {
              "text": "MasterClass workshop available (4x yearly) for online teaching experience and networking",
              "done": false
            }
          ],
          "granola": "https://notes.granola.ai/d/d15ab3b8-71e0-4f2d-beb3-72250f904578",
          "transcriptUrl": "https://notes.granola.ai/t/3347ac23-8206-4f3e-a676-d296366fdf10",
          "source": "Granola"
        }
      ],
      "calendarMeetings": [
        {
          "date": "2026-04-06",
          "time": "8:30 AM",
          "label": "Send email follow up for BST 606",
          "uid": "040000008200E00074C5B7101A82E00800000000CA5923B5DCC2DC010000000000000000100000002404B511998B3B4E962598059F9602C4"
        }
      ]
    },
    "tph552": {
      "lastActiveDate": "2026-04-02",
      "lastActive": "16 days ago",
      "actionItems": {
        "total": 7,
        "done": 0,
        "pending": [
          "Unnamed colleague (course lead)",
          "Confirm with Ina that she’s comfortable with the collapsed objectives structure",
          "Clean up and finalize the course map at next meeting",
          "Resolve notes column in the mapping document",
          "Help leadership understand accreditation implications extend beyond SAFE to ABOR",
          "Elisa: Continue development of assignments overview and materials overview pages (drag-between-modules feature in progress)",
          "Elisa: Join the other call/session after this meeting"
        ]
      },
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 18",
        "text": "Vienna teaching the in-person version; now working on the in-person/online course for summer. Not due until summer 2027 — she’s starting early",
        "source": "granola"
      },
      "nextMeeting": null,
      "milestoneStatus": [],
      "milestones": [],
      "meetings": [
        {
          "date": "Apr 2, 2026",
          "title": "TPH 552",
          "people": [
            "Elisa Penmar"
          ],
          "summary": "Vienna teaching the in-person version; now working on the in-person/online course for summer. Not due until summer 2027 — she’s starting early",
          "decisions": [],
          "actionItems": [
            {
              "text": "Unnamed colleague (course lead)",
              "done": false
            },
            {
              "text": "Confirm with Ina that she’s comfortable with the collapsed objectives structure",
              "done": false
            },
            {
              "text": "Clean up and finalize the course map at next meeting",
              "done": false
            },
            {
              "text": "Resolve notes column in the mapping document",
              "done": false
            },
            {
              "text": "Help leadership understand accreditation implications extend beyond SAFE to ABOR",
              "done": false
            },
            {
              "text": "Elisa: Continue development of assignments overview and materials overview pages (drag-between-modules feature in progress)",
              "done": false
            },
            {
              "text": "Elisa: Join the other call/session after this meeting",
              "done": false
            }
          ],
          "granola": "https://notes.granola.ai/d/ac4acd7b-ac09-4e64-8184-671704f78e0f",
          "transcriptUrl": "https://notes.granola.ai/t/fda801ef-e051-47f3-b296-2844dfb9720e",
          "source": "Granola"
        }
      ]
    },
    "tph557": {
      "calendarMeetings": [
        {
          "date": "2026-04-23",
          "time": "11:00 AM",
          "label": "TPH 557 - Module Objective Allignment",
          "uid": "040000008200E00074C5B7101A82E008000000000006834CD2C6DC010000000000000000100000007E46AADE2426A543A82A1A698CDDF3C3"
        }
      ],
      "nextMeeting": {
        "date": "2026-04-23",
        "time": "11:00 AM",
        "label": "TPH 557 - Module Objective Allignment"
      },
      "meetings": [
        {
          "date": "Apr 7, 2026",
          "title": "TPH 557 Course Development Kickoff",
          "people": [
            "Tamara Mitchell",
            "Other: Rachel (faculty member for TPH 557)"
          ],
          "summary": "TPH 557 ethics course moving from in-person to online format. Fall 2026 launch date scheduled",
          "decisions": [],
          "actionItems": [],
          "granola": "https://notes.granola.ai/d/73bc3764-54eb-4150-af82-e4e3b59e92d4",
          "transcriptUrl": "https://notes.granola.ai/t/f0e2c8de-91d1-4c50-a797-12673cc8b1c1",
          "source": "Granola"
        }
      ],
      "actionItems": {
        "total": 0,
        "done": 0,
        "pending": []
      },
      "lastActiveDate": "2026-04-07",
      "lastActive": "11 days ago",
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 18",
        "text": "TPH 557 ethics course moving from in-person to online format. Fall 2026 launch date scheduled",
        "source": "granola"
      }
    },
    "tph550": {
      "calendarMeetings": [
        {
          "date": "2026-04-20",
          "time": "2:00 PM",
          "label": "TPH 550 Devo Meeting",
          "uid": "040000008200E00074C5B7101A82E0080000000028CB520511C6DC01000000000000000010000000C8667B0A1A520342BBC8CA1F6F20406E"
        }
      ],
      "nextMeeting": {
        "date": "2026-04-20",
        "time": "2:00 PM",
        "label": "TPH 550 Devo Meeting"
      },
      "lastActiveDate": "2026-04-06",
      "lastActive": "9 days ago",
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 6",
        "text": "Pending: Josh to fill in module topics in course planning worksheet by Apr 11; send recap email with worksheet link; map objectives to 7-module structure after Josh submits topics; confirm AI persona (William Compton) integration scope before Apr 20 meeting. Recent decisions: Converting 15-week in-person course to 7-week online (7 modules); ~80% Python, dropping R/RStudio; all lectures must be recorded before Josh leaves for Europe end of June; final project will use menu of datasets with option for self-directed choice.",
        "source": "granola"
      },
      "meetings": [
        {
          "date": "Apr 6, 2026",
          "title": "TPH 550 Course Development Kickoff",
          "people": [
            "Elisa Penmar",
            "Josh Loughman"
          ],
          "summary": "Kickoff meeting for converting TPH 550 from 15-week in-person to 7-week online. Josh must record all lectures before European travel in July. Course will shift to ~80% Python, dropping R. Final project structure to use dataset menu approach for scalability to ~50 students.",
          "decisions": [
            "Converting 15-week in-person course to 7-week online (7 modules)",
            "Language shift to ~80% Python, dropping R/RStudio",
            "All lectures must be recorded before Josh leaves for Europe end of June",
            "Final project: menu of datasets with option for self-directed choice",
            "Josh will target September cohort for ASU Online Masterclass instead of July"
          ],
          "actionItems": [
            {
              "text": "Josh: Fill in module topics in course planning worksheet by Apr 11",
              "done": false
            },
            {
              "text": "Josh: Connect with Sarah Hoyt and Mark to confirm accreditation deadline and course objectives",
              "done": false
            },
            {
              "text": "Josh: Consider final project structure (menu vs. open-ended dataset selection)",
              "done": false
            },
            {
              "text": "Elisa & Tamara: Send recap email with link to course planning/development worksheet",
              "done": false
            },
            {
              "text": "Elisa & Tamara: Map existing objectives to new 7-module structure after Josh submits topics",
              "done": false
            },
            {
              "text": "Elisa: Send calendar invite for follow-up meeting Monday Apr 20 at 2:00 PM",
              "done": true
            },
            {
              "text": "Tamara: Confirm AI persona (William Compton) integration scope before Apr 20 meeting",
              "done": false
            },
            {
              "text": "Tamara: Loop Elisa into journal paper meeting with Mark",
              "done": false
            }
          ],
          "granola": "https://notes.granola.ai/d/1927ef1b-b723-4929-8e4c-46460f190eea",
          "source": "Granola"
        }
      ],
      "actionItems": {
        "total": 8,
        "done": 1,
        "pending": [
          "Josh: Fill in module topics in course planning worksheet by Apr 11",
          "Josh: Connect with Sarah Hoyt and Mark to confirm accreditation deadline",
          "Elisa & Tamara: Send recap email with worksheet link",
          "Elisa & Tamara: Map objectives to 7-module structure",
          "Tamara: Confirm AI persona integration scope before Apr 20",
          "Tamara: Loop Elisa into journal paper meeting with Mark",
          "Josh: Consider final project structure"
        ]
      }
    },
    "tph501": {
      "calendarMeetings": [
        {
          "date": "2026-04-22",
          "time": "9:00 AM",
          "label": "TPH 501 - Assignments",
          "uid": "040000008200E00074C5B7101A82E00800000000A01D8CB3BACEDC01000000000000000010000000826A6F43A4CCA4468B3FFEB5A836AFC0"
        }
      ],
      "nextMeeting": {
        "date": "2026-04-22",
        "time": "9:00 AM",
        "label": "TPH 501 - Assignments"
      },
      "meetings": [
        {
          "date": "Apr 17, 2026",
          "title": "TPH 501 course development with Josh and Jordan",
          "people": [
            "Tamara Mitchell",
            "Other: Josh Anbar"
          ],
          "summary": "TPH 501 is undergoing complete redevelopment for both online and in-person delivery. Course must be completed by August for fall launch",
          "decisions": [],
          "actionItems": [],
          "granola": "https://notes.granola.ai/d/c065a381-c7db-4edb-82d2-9b13713f177f",
          "transcriptUrl": "https://notes.granola.ai/t/910e7332-f8fb-47eb-8b11-417e82e31318",
          "source": "Granola"
        }
      ],
      "actionItems": {
        "total": 0,
        "done": 0,
        "pending": []
      },
      "lastActiveDate": "2026-04-17",
      "lastActive": "Yesterday",
      "notes": {
        "author": "Elisa Penmar",
        "date": "Apr 18",
        "text": "TPH 501 is undergoing complete redevelopment for both online and in-person delivery. Course must be completed by August for fall launch",
        "source": "granola"
      }
    },
    "tph585": {
      "calendarMeetings": [
        {
          "date": "2026-05-12",
          "time": "11:30 AM",
          "label": "Capstone Celebration! RSVP Today!",
          "uid": "040000008200E00074C5B7101A82E0080000000030F376128EC3DC010000000000000000100000002405621BEC5A624ABD71B605B4349FEF"
        }
      ],
      "nextMeeting": {
        "date": "2026-05-12",
        "time": "11:30 AM",
        "label": "Capstone Celebration! RSVP Today!"
      }
    }
  },
  "upcomingDeadlines": [
    {
      "date": "2026-04-24",
      "month": "Apr",
      "day": "24",
      "title": "CLOs and ELOs Due",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "urgent": true,
      "hasMeeting": true,
      "meetingTime": "8:00 AM",
      "meetingLabel": "BST 605 Assignment Review "
    },
    {
      "date": "2026-04-30",
      "month": "Apr",
      "day": "30",
      "title": "Materials Review (2:00 PM)",
      "course": "MNS 521 — AI Technologies (Navabi)",
      "hasMeeting": true,
      "meetingTime": "1:30 PM",
      "meetingLabel": "MNS 521 - Module 1",
      "urgent": true
    },
    {
      "date": "2026-07-20",
      "month": "Jul",
      "day": "20",
      "title": "Course Shell Due",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "hasMeeting": false
    },
    {
      "date": "2026-08-01",
      "month": "Aug",
      "day": "1",
      "title": "Final Walkthrough & QA",
      "course": "MNS 521 — AI Technologies (Navabi)",
      "hasMeeting": false
    },
    {
      "date": "2026-08-17",
      "month": "Aug",
      "day": "17",
      "title": "Student Access / Launch",
      "course": "BST 605 — Biostatistical Data Analysis (Habte)",
      "hasMeeting": false
    },
    {
      "date": "2026-09-14",
      "month": "Sep",
      "day": "14",
      "title": "QA Deadline",
      "course": "BST 606 — Applied Clinical Trial Design (Yunro Chung)",
      "hasMeeting": false
    },
    {
      "date": "2026-10-14",
      "month": "Oct",
      "day": "14",
      "title": "Session B Launch",
      "course": "BST 606 — Applied Clinical Trial Design (Yunro Chung)",
      "hasMeeting": false
    }
  ],
  "calendarSyncedAt": "2026-04-18T17:49:39.426Z",
  "notesSyncedAt": "2026-04-18T18:27:28.877Z"
};
